<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16869" started-at="2025-01-30T05:55:23Z" finished-at="2025-01-30T05:55:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16869" started-at="2025-01-30T05:55:23Z" finished-at="2025-01-30T05:55:40Z">
      <class name="EretailRest.EretailAPI.tests.crud.VerifyOrderProcessApi">
        <test-method status="PASS" signature="setUp()[pri:0, instance:EretailRest.EretailAPI.tests.crud.VerifyOrderProcessApi@64cd705f]" name="setUp" is-config="true" duration-ms="20" started-at="2025-01-30T11:25:23Z" finished-at="2025-01-30T11:25:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyOrderProcessApi()[pri:0, instance:EretailRest.EretailAPI.tests.crud.VerifyOrderProcessApi@64cd705f]" name="verifyOrderProcessApi" duration-ms="16616" started-at="2025-01-30T11:25:23Z" finished-at="2025-01-30T11:25:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
expected: "CHEA0C106009"
 but was: null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
expected: "CHEA0C106009"
 but was: null
	at EretailRest.EretailAPI.tests.crud.VerifyOrderProcessApi.verifyOrderProcessApi(VerifyOrderProcessApi.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderProcessApi -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:EretailRest.EretailAPI.tests.crud.VerifyOrderProcessApi@64cd705f]" name="tearDown" is-config="true" duration-ms="11" started-at="2025-01-30T11:25:40Z" finished-at="2025-01-30T11:25:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- EretailRest.EretailAPI.tests.crud.VerifyOrderProcessApi -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
