<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="6" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="27454" started-at="2025-05-16T05:27:18Z" finished-at="2025-05-16T05:27:45Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="27454" started-at="2025-05-16T05:27:18Z" finished-at="2025-05-16T05:27:45Z">
      <class name="Eretail.FrameworkEretail.tests.EretailLogin">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="startBrowser" is-config="true" duration-ms="25579" started-at="2025-05-16T10:56:52Z" finished-at="2025-05-16T10:57:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="PASS" signature="TC001()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="TC001" duration-ms="8149" started-at="2025-05-16T10:57:18Z" finished-at="2025-05-16T10:57:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="closeBrowser" is-config="true" duration-ms="44" started-at="2025-05-16T10:57:26Z" finished-at="2025-05-16T10:57:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="FAIL" signature="TC002()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="TC002" duration-ms="1312" started-at="2025-05-16T10:57:26Z" finished-at="2025-05-16T10:57:28Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to eRetail] but found [Login Failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to eRetail] but found [Login Failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Eretail.FrameworkEretail.tests.EretailLogin.TC002(EretailLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="closeBrowser" is-config="true" duration-ms="4" started-at="2025-05-16T10:57:28Z" finished-at="2025-05-16T10:57:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="FAIL" signature="TC002()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="TC002" duration-ms="1019" started-at="2025-05-16T10:57:28Z" finished-at="2025-05-16T10:57:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to eRetail] but found [Login Failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to eRetail] but found [Login Failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Eretail.FrameworkEretail.tests.EretailLogin.TC002(EretailLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="closeBrowser" is-config="true" duration-ms="45" started-at="2025-05-16T10:57:29Z" finished-at="2025-05-16T10:57:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="FAIL" signature="TC002()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="TC002" duration-ms="1040" started-at="2025-05-16T10:57:29Z" finished-at="2025-05-16T10:57:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to eRetail] but found [Login Failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to eRetail] but found [Login Failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Eretail.FrameworkEretail.tests.EretailLogin.TC002(EretailLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="closeBrowser" is-config="true" duration-ms="7" started-at="2025-05-16T10:57:30Z" finished-at="2025-05-16T10:57:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="FAIL" signature="TC002()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="TC002" duration-ms="1082" started-at="2025-05-16T10:57:30Z" finished-at="2025-05-16T10:57:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to eRetail] but found [Login Failed]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to eRetail] but found [Login Failed]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at Eretail.FrameworkEretail.tests.EretailLogin.TC002(EretailLogin.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC002 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.EretailLogin@503f91c3]" name="closeBrowser" is-config="true" duration-ms="34" started-at="2025-05-16T10:57:31Z" finished-at="2025-05-16T10:57:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Eretail.FrameworkEretail.tests.EretailLogin -->
      <class name="Eretail.FrameworkEretail.tests.dummy1">
        <test-method status="PASS" signature="TC001()[pri:0, instance:Eretail.FrameworkEretail.tests.dummy1@7975d1d8]" name="TC001" duration-ms="14385" started-at="2025-05-16T10:57:31Z" finished-at="2025-05-16T10:57:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Eretail.FrameworkEretail.tests.dummy1@7975d1d8]" name="closeBrowser" is-config="true" duration-ms="5" started-at="2025-05-16T10:57:45Z" finished-at="2025-05-16T10:57:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Eretail.FrameworkEretail.tests.dummy1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
