<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="4.236">
    <properties></properties>

            <testcase
                name="testVerifyCreateBookingPostTC01"
                time="4.236"
                classname="Assured.restAssuredFramework.Tests.Crud.TestCreateBookingPost">

            <failure type="java.lang.AssertionError" message="
expected: &quot;nehra&quot;
 but was: &quot;nehra1&quot;">
                <![CDATA[java.lang.AssertionError: 
expected: "nehra"
 but was: "nehra1"
                Assured.restAssuredFramework.Tests.Crud.TestCreateBookingPost.testVerifyCreateBookingPostTC01(TestCreateBookingPost.java:44)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:483)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)org.testng.internal.Invoker.invokeMethod(Invoker.java:714)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)org.testng.TestRunner.privateRun(TestRunner.java:767)org.testng.TestRunner.run(TestRunner.java:617)org.testng.SuiteRunner.runTest(SuiteRunner.java:348)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)org.testng.SuiteRunner.run(SuiteRunner.java:254)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)org.testng.TestNG.runSuitesLocally(TestNG.java:1149)org.testng.TestNG.run(TestNG.java:1057)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </failure>
    </testcase>


</testsuite>
